export enum ActionTypes {
  DISPLAY_ALERT = 'DISPLAY_ALERT',
  CLEAR_ALERT = 'CLEAR_ALERT',
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  REGENERATE_ACCESS_TOKEN = 'REGENERATE_ACCESS_TOKEN',
  LOGOUT_USER = 'LOGOUT_USER',
  UPDATE_USER_BASIC_INFO = 'UPDATE_USER_BASIC_INFO',
  SET_STORAGE_LOADING = 'SET_STORAGE_LOADING',
  SET_INITIAL_STATE = 'SET_INITIAL_STATE',
}
